<?php

use lispa\amos\core\forms\ActiveForm;
use lispa\amos\core\forms\CloseSaveButtonWidget;
use lispa\amos\core\forms\CreatedUpdatedWidget;
use lispa\amos\sondaggi\AmosSondaggi;
use lispa\amos\sondaggi\assets\ModuleSondaggiAsset;
use kartik\widgets\DepDrop;
use kartik\widgets\Select2;
use yii\bootstrap\Tabs;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;

ModuleSondaggiAsset::register($this);

/**
 * @var yii\web\View $this
 * @var lispa\amos\sondaggi\models\SondaggiDomande $model
 * @var yii\widgets\ActiveForm $form
 */
$js = <<< JS
       /* setTimeout(
        function() 
        {           */
        $("#ordina_dopo").prop("disabled", true); 
       /* }, 1200);                        */
JS;

$this->registerJs($js, yii\web\View::POS_LOAD);
?>

<div class="sondaggi-domande-form">
    
    <?php $form = ActiveForm::begin(); ?>
    
    <?php $this->beginBlock('generale'); ?>
    <div class="row sondaggio-row">
        <div class="col-sm-12">
            <?= $form->field($model, 'domanda', ['options' => ['class' => 'nom']])->textarea(['rows' => 4]) ?>
        </div>
        <div class="col-sm-6">
            <!--                <label>Opzioni</label>-->
            <?= $form->field($model, 'obbligatoria')->checkbox() ?>
        </div>
    </div>
    <div class="row sondaggio-row">
        <?php if ($model->sondaggi_id) : ?>
            <div class="col-xs-12">
                <?= $form->field($model, 'ordine', ['options' => ['class' => 'nom']])->inline()->radioList(['inizio' => AmosSondaggi::t('amossondaggi', "All'inizio"), 'fine' => AmosSondaggi::t('amossondaggi', 'Alla fine'), 'dopo' => AmosSondaggi::t('amossondaggi', 'Dopo la seguente domanda')], ['id' => 'ordinamento-radio'])->label(AmosSondaggi::t('amossondaggi', 'Posiziona la domanda') . ':') ?>
            </div>
            <!--?= $form->field($model, 'ordina_dopo')->dropDownList(ArrayHelper::map($model->getTutteDomandeSondaggio()->all(), 'id', 'domanda'), ['id' => 'ordina-dopo'])->label(''); ?-->
            <div class="col-xs-12">
                <?=
                $form->field($model, 'ordina_dopo')->widget(DepDrop::classname(), [
                    //'type' => DepDrop::TYPE_SELECT2,
                    'data' => $model->getDomandaPrecedente() ? [$model->getDomandaPrecedente() => lispa\amos\sondaggi\models\SondaggiDomande::findOne($model->getDomandaPrecedente())->domanda] : [],
                    'options' => ['id' => 'ordina_dopo'],
                    //'select2Options' => ['pluginOptions' => ['allowClear' => false]],
                    'pluginOptions' => [
                        'depends' => ['sondaggi_domande_pagine_id-id'],
                        'placeholder' => ['Seleziona ...'],
                        'url' => Url::to(['/' . $this->context->module->id . '/ajax/domande-by-pagine']),
                        'initialize' => true,
                        'params' => ['ordina_dopo'],
                    ],
                ])->label(false);
                ?>
            </div>
        <?php else: ?>
            <div class="col-xs-12 nom">
                <?= $form->field($model, 'ordine')->inline()->radioList(['inizio' => 'All\'inizio', 'fine' => 'Alla fine'])->label('Posiziona la domanda:') ?>
            </div>
        <?php endif; ?>
    </div>
    <div class="row sondaggio-row">
        <div class="col-lg-6 col-sm-6">
            <?=
            // generated by schmunk42\giiant\crud\providers\RelationProvider::activeField 
            $form->field($model, 'sondaggi_domande_tipologie_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(\lispa\amos\sondaggi\models\SondaggiDomandeTipologie::find()->andWhere(['attivo' => 1])->all(), 'id', 'tipologia'), ['prompt' => AmosSondaggi::t('amossondaggi', 'Seleziona il tipo di risposta ...')]
            );
            ?>
        </div>
        <div class="col-lg-6 col-sm-6">
            <?=
            $form->field($model, 'inline')->dropDownList([0 => 'In colonna (una sotto l\'altra)', 1 => 'In linea (sulla stessa linea)']);
            ?>
        </div>
    </div>
    <div class="row" id="selezione-classe-validatrice">
        <div class="col-lg-12 col-sm-12">
            <?= $form->field($model, 'nome_classe_validazione')->textInput(); ?>
        </div>
    </div>
    <div class="row" id="selezioni-minime-massime-label">
        <div class="col-lg-12 col-sm-12">
            <?php
            $model->min_int_multipla = ($model->min_int_multipla) ? $model->min_int_multipla : 0;
            $model->max_int_multipla = ($model->max_int_multipla) ? $model->max_int_multipla : 0;
            ?>
            <p><i><?= AmosSondaggi::t('amossondaggi', 'Selezioni minime e/o massime se impostate a "0" (vuol dire senza limiti) non avranno nessuno effetto.') ?></i></p>
        </div>
    </div>
    <div class="row" id="selezioni-minime-massime">
        <div class="col-lg-6 col-sm-6">
            <?=
            $form->field($model, 'min_int_multipla')->textInput();
            ?>
        </div>
        <div class="col-lg-6 col-sm-6">
            <?=
            $form->field($model, 'max_int_multipla')->textInput();
            ?>
        </div>
    </div>
    <div class="row">

        <div class="col-lg-6 col-sm-6">
            <?php
            if ($model->sondaggi_id) :
                $model->sondaggi_id = $model->sondaggi_id;
                ?>
                <?=
                $form->field($model, 'sondaggi_id')->widget(Select2::classname(), [
                    'data' => ArrayHelper::map(\lispa\amos\sondaggi\models\Sondaggi::find()->asArray()->all(), 'id', 'titolo'),
                    'options' => ['placeholder' => AmosSondaggi::t('amossondaggi', 'Digita il nome del sondaggio ...'), 'id' => 'sondaggi_id-id', 'disabled' => TRUE],
                ]);
                ?>
                <?= $form->field($model, 'sondaggi_id')->hiddenInput()->label(FALSE); ?>
            <?php else : ?>
                <?=
                $form->field($model, 'sondaggi_id')->widget(Select2::classname(), [
                    'data' => ArrayHelper::map(\lispa\amos\sondaggi\models\Sondaggi::find()->asArray()->all(), 'id', 'titolo'),
                    'options' => ['placeholder' => AmosSondaggi::t('amossondaggi', 'Digita il nome del sondaggio ...'), 'id' => 'sondaggi_id-id'],
                ]);
                ?>
            <?php endif; ?>
        </div>
        <div class="col-lg-6 col-sm-6">
            <?=
            $form->field($model, 'sondaggi_domande_pagine_id')->widget(DepDrop::classname(), [
                //'type' => DepDrop::TYPE_SELECT2,
                'data' => $model->sondaggi_domande_pagine_id ? [$model->getSondaggiDomandePagine()->one()->id => $model->getSondaggiDomandePagine()->one()->titolo] : [],
                'options' => ['id' => 'sondaggi_domande_pagine_id-id'],
                //'select2Options' => ['pluginOptions' => ['allowClear' => false]],
                'pluginOptions' => [
                    'depends' => ['sondaggi_id-id'],
                    'placeholder' => ['Seleziona ...'],
                    'url' => Url::to(['/' . $this->context->module->id . '/ajax/pagine-by-sondaggio']),
                    'initialize' => true,
                    'params' => ['sondaggi_domande_pagine_id-id'],
                ],
            ]);
            ?>
        </div>
    </div>

    <div class="row">

        <div class="col-lg-3 col-sm-3">
            <label></label>
            <?= $form->field($model, 'domanda_condizionata')->checkbox(['id' => 'domcond']) ?>
        </div>
        <div class="col-lg-9 col-sm-9">
            <?php
            if ($model->domanda_condizionata) :
                $model->condizione_necessaria = $model->getSondaggiRispostePredefinitesCondizionate()->one()['id'];
            endif;
            ?>
            <?=
            $form->field($model, 'condizione_necessaria')->dropDownList(
                yii\helpers\ArrayHelper::map($model->getRispostePredefiniteSondaggio()->all(), 'id', 'risposta', 'domanda'), ['id' => 'condizione_necessaria-id']
            )
            ?>
            <?php /*
              $form->field($model, 'condizione_necessaria')->widget(DepDrop::classname(), [
              'type' => DepDrop::TYPE_SELECT2,
              'data' => $model->domanda_condizionata ? [$model->getSondaggiRispostePredefinitesCondizionate()->one()['id'] => $model->getSondaggiRispostePredefinitesCondizionate()->one()['risposta']] : [],
              'options' => ['id' => 'condizione_necessaria-id', 'enabled' => TRUE],
              'select2Options' => ['pluginOptions' => ['allowClear' => true]],
              'pluginOptions' => [
              'depends' => ['sondaggi_id-id'],
              'placeholder' => ['Seleziona ...'],
              'url' => Url::to(['/' . $this->context->module->id . '/ajax/condizione-by-risposta']),
              'initialize' => true,
              'params' => ['sondaggi_id-id'],
              ],
              ]);
             */ ?>
        </div>

    </div>

    <div class="col-lg-6 col-sm-6">

    </div>
    <div class="clearfix"></div>
    <?php $this->endBlock(); ?>
    
    <?php
    $itemsTab[] = [
        'label' => AmosSondaggi::t('amossondaggi', 'generale '),
        'content' => $this->blocks['generale'],
    ];
    ?>
    
    <?=
    Tabs::widget(
        [
            'encodeLabels' => false,
            'items' => $itemsTab
        ]
    );
    ?>
    <?= CreatedUpdatedWidget::widget(['model' => $model]) ?>
    <div id="form-actions" class="bk-btnFormContainer">
        <?php if (isset($model->sondaggi_id) && isset($model->sondaggi_domande_pagine_id) && !$url) : ?>
            <?= Html::submitButton(AmosSondaggi::tHtml('amossondaggi', 'Inserisci e vai a nuova pagina'), ['class' => 'btn btn-success', 'id' => 'submit-pagina', 'name' => 'pagina']); ?>
            <?= CloseSaveButtonWidget::widget([
                'model' => $model,
                'buttonNewSaveLabel' => $model->isNewRecord ? 'Inserisci' : 'Salva',
            ]); ?>
        <?php else : ?>
            <?= CloseSaveButtonWidget::widget([
                'model' => $model,
                'buttonNewSaveLabel' => $model->isNewRecord ? 'Inserisci' : 'Salva',
            ]);
            ?>
        <?php endif; ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>
