<?php

namespace open20\amos\sondaggi\assets;

use yii\web\AssetBundle;

class ModuleRisultatiAsset extends AssetBundle
{
    public $sourcePath = '@vendor/open20/amos-sondaggi/src/assets/web';

    public $css = [
        'less/sondaggi-fullsize.less',
    ];
    public $js = [        
    ];
    public $depends = [        
        'yii\web\JqueryAsset',
        'yii\jui\JuiAsset',
        //'kartik\depdrop\DepDropAsset',
        'kartik\depdrop\DepDropExtAsset'
    ];

    public function init()
    {
        $moduleL = \Yii::$app->getModule('layout');
        if(!empty($moduleL))
        { $this->depends [] = 'open20\amos\layout\assets\BaseAsset'; }
        else
        { $this->depends [] = 'open20\amos\core\views\assets\AmosCoreAsset'; }
        parent::init(); // TODO: Change the autogenerated stub
    }
}
