<?php

namespace lispa\amos\sondaggi\assets;

use yii\web\AssetBundle;

class ModuleSondaggiRisposteAsset extends AssetBundle
{
    public $sourcePath = '@vendor/lispa/amos-sondaggi/src/assets/web';

    public $css = [
    ];
    public $js = [
        'js/condizioneRisposteSondaggio.js'
    ];
    public $depends = [        
        'yii\web\JqueryAsset',
        'yii\jui\JuiAsset'
    ];

    public function init()
    {
        $moduleL = \Yii::$app->getModule('layout');
        if(!empty($moduleL))
        { $this->depends [] = 'lispa\amos\layout\assets\BaseAsset'; }
        else
        { $this->depends [] = 'lispa\amos\core\views\assets\AmosCoreAsset'; }
        parent::init(); // TODO: Change the autogenerated stub
    }
}
